### ISSUE TITLE
persistgraphql library not found on yarn install

### ISSUE THREAD

**Issue by kostajh** [fubhy/drupal-decoupled-app#381]
`yarn install` fails with:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@amazee/persistgraphql/-/persistgraphql-0.3.2.tgz: Request failed \"404 Not Found\"".
```

Stack trace:

```
Trace:
  Error: https://registry.yarnpkg.com/@amazee/persistgraphql/-/persistgraphql-0.3.2.tgz: Request failed "404 Not Found"
      at Request.handleRequestError (/usr/local/Cellar/yarn/0.23.2/libexec/lib/fetchers/tarball-fetcher.js:205:20)
      at emitOne (events.js:96:13)
      at Request.emit (events.js:191:7)
      at Request.onRequestResponse (/usr/local/Cellar/yarn/0.23.2/libexec/node_modules/request/request.js:1074:10)
      at emitOne (events.js:96:13)
      at ClientRequest.emit (events.js:191:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:522:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
      at TLSSocket.socketOnData (_http_client.js:411:20)
      at emitOne (events.js:96:13)
      at TLSSocket.emit (events.js:191:7)
```

**Comment by fubhy** [comment]
Hi @kostajh,

Thanks for the report. I just tried installing again after removing all my npm login credentials etc. and it worked. Can you try again now? Maybe the registry was a bit slow...

**Comment by fubhy** [comment]
This should work now.
